//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neovolve.BuildTaskExecutor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Neovolve.BuildTaskExecutor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The OutputType node does not contain a value of WinExe, Exe or Library..
        /// </summary>
        internal static string BinaryOutputVersionTask_InvalidOutputTypeValue {
            get {
                return ResourceManager.GetString("BinaryOutputVersionTask_InvalidOutputTypeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project does not contain the AssemblyName node..
        /// </summary>
        internal static string BinaryOutputVersionTask_NoAssemblyNameNode {
            get {
                return ResourceManager.GetString("BinaryOutputVersionTask_NoAssemblyNameNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project does not contain an AssemblyName value..
        /// </summary>
        internal static string BinaryOutputVersionTask_NoAssemblyNameValue {
            get {
                return ResourceManager.GetString("BinaryOutputVersionTask_NoAssemblyNameValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project does not contain the OutputType node..
        /// </summary>
        internal static string BinaryOutputVersionTask_NoOutputTypeNode {
            get {
                return ResourceManager.GetString("BinaryOutputVersionTask_NoOutputTypeNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BuildTaskExecutor - Neovolve Build Task Executor {0}.
        /// </summary>
        internal static string Executor_ApplicationInformation {
            get {
                return ResourceManager.GetString("Executor_ApplicationInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing task &apos;{0}&apos;..
        /// </summary>
        internal static string Executor_ExecutingTask {
            get {
                return ResourceManager.GetString("Executor_ExecutingTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The arguments passed to the task &apos;{0}&apos; were invalid..
        /// </summary>
        internal static string Executor_InvalidTaskArguments {
            get {
                return ResourceManager.GetString("Executor_InvalidTaskArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No task execution arguments provided..
        /// </summary>
        internal static string Executor_NoArgumentsProvided {
            get {
                return ResourceManager.GetString("Executor_NoArgumentsProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /el:	Event writing level - critical|error|warning|information|verbose.
        /// </summary>
        internal static string HelpTask_EventLevelHelp {
            get {
                return ResourceManager.GetString("HelpTask_EventLevelHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type BuildTaskExecutor help for command line description.
        /// </summary>
        internal static string HelpTask_GenericHelpCommandLine {
            get {
                return ResourceManager.GetString("HelpTask_GenericHelpCommandLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BuildTaskExecutor {0} {1}.
        /// </summary>
        internal static string HelpTask_TaskCommandLineHelp {
            get {
                return ResourceManager.GetString("HelpTask_TaskCommandLineHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type BuildTaskExecutor [/el:&lt;event level&gt;] &lt;task name&gt; [arg0 arg1 ... argn].
        /// </summary>
        internal static string HelpTask_TaskExecuteCommandLine {
            get {
                return ResourceManager.GetString("HelpTask_TaskExecuteCommandLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type BuildTaskExecutor help &lt;task name&gt; for task description.
        /// </summary>
        internal static string HelpTask_TaskHelpCommandLine {
            get {
                return ResourceManager.GetString("HelpTask_TaskHelpCommandLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BuildTaskExecutor {0}
        ///{1}
        ///.
        /// </summary>
        internal static string HelpTask_TaskHelpDescription {
            get {
                return ResourceManager.GetString("HelpTask_TaskHelpDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks:.
        /// </summary>
        internal static string HelpTask_TaskListHeader {
            get {
                return ResourceManager.GetString("HelpTask_TaskListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating file &apos;{0}&apos; from version &apos;{1}&apos; to &apos;{2}&apos;..
        /// </summary>
        internal static string IncrementAssemblyVersionTask_FileUpdateNotification {
            get {
                return ResourceManager.GetString("IncrementAssemblyVersionTask_FileUpdateNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying &apos;{0}&apos; to &apos;{1}&apos;..
        /// </summary>
        internal static string ProjectOutputVersionTask_FileCopyNotification {
            get {
                return ResourceManager.GetString("ProjectOutputVersionTask_FileCopyNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving &apos;{0}&apos; to &apos;{1}&apos;..
        /// </summary>
        internal static string ProjectOutputVersionTask_FileMoveNotification {
            get {
                return ResourceManager.GetString("ProjectOutputVersionTask_FileMoveNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project file does not contain any build configurations..
        /// </summary>
        internal static string ProjectOutputVersionTask_NoBuildConfigurationsFound {
            get {
                return ResourceManager.GetString("ProjectOutputVersionTask_NoBuildConfigurationsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No project output files were found.
        /// </summary>
        internal static string ProjectOutputVersionTask_NoOutputFound {
            get {
                return ResourceManager.GetString("ProjectOutputVersionTask_NoOutputFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to identify project output name property..
        /// </summary>
        internal static string ProjectOutputVersionTask_OutputNameNotFound {
            get {
                return ResourceManager.GetString("ProjectOutputVersionTask_OutputNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading project file &apos;{0}&apos;..
        /// </summary>
        internal static string ProjectOutputVersionTask_ProjectLoadNotification {
            get {
                return ResourceManager.GetString("ProjectOutputVersionTask_ProjectLoadNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping missing directory &apos;{0}&apos;..
        /// </summary>
        internal static string ProjectOutputVersionTask_SkippingDirectoryNotification {
            get {
                return ResourceManager.GetString("ProjectOutputVersionTask_SkippingDirectoryNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found. Skipping file &apos;{0}&apos;..
        /// </summary>
        internal static string ProjectOutputVersionTask_SkippingFileNotification {
            get {
                return ResourceManager.GetString("ProjectOutputVersionTask_SkippingFileNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating wix project &apos;{0}&apos; from version &apos;{1}&apos; to &apos;{2}&apos;..
        /// </summary>
        internal static string SyncWixVersionTask_FileUpdateNotification {
            get {
                return ResourceManager.GetString("SyncWixVersionTask_FileUpdateNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; matches the following tasks:.
        /// </summary>
        internal static string TaskResolver_MatchingTasksHeader {
            get {
                return ResourceManager.GetString("TaskResolver_MatchingTasksHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple tasks found for the name &apos;{0}&apos;..
        /// </summary>
        internal static string TaskResolver_MultipleTasksFound {
            get {
                return ResourceManager.GetString("TaskResolver_MultipleTasksFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found task &apos;{0}&apos; as {1}.
        /// </summary>
        internal static string TaskResolver_TaskFound {
            get {
                return ResourceManager.GetString("TaskResolver_TaskFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The task &apos;{0}&apos; was not found..
        /// </summary>
        internal static string TaskResolver_TaskNotFound {
            get {
                return ResourceManager.GetString("TaskResolver_TaskNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to resolve task &apos;{0}&apos;..
        /// </summary>
        internal static string TaskResolver_TaskResolutionAttempt {
            get {
                return ResourceManager.GetString("TaskResolver_TaskResolutionAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking out file &apos;{0}&apos;..
        /// </summary>
        internal static string TfsCheckoutTask_CheckingOutFile {
            get {
                return ResourceManager.GetString("TfsCheckoutTask_CheckingOutFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using &apos;{0}&apos; to check out files..
        /// </summary>
        internal static string TfsCheckoutTask_CheckOutNotification {
            get {
                return ResourceManager.GetString("TfsCheckoutTask_CheckOutNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to check out file &apos;{0}&apos; from TFS..
        /// </summary>
        internal static string TfsCheckoutTask_FileCheckOutFailed {
            get {
                return ResourceManager.GetString("TfsCheckoutTask_FileCheckOutFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to identify version information in project &apos;{0}&apos;..
        /// </summary>
        internal static string VersionAction_VersionNotFound {
            get {
                return ResourceManager.GetString("VersionAction_VersionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string WildcardFileSearchTask_DirectoryNotFound {
            get {
                return ResourceManager.GetString("WildcardFileSearchTask_DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for matching files under &apos;{0}&apos;..
        /// </summary>
        internal static string WildcardFileSearchTask_SearchingDirectory {
            get {
                return ResourceManager.GetString("WildcardFileSearchTask_SearchingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The OutputName node does not contain a value..
        /// </summary>
        internal static string WixOutputVersionTask_NoOutputName {
            get {
                return ResourceManager.GetString("WixOutputVersionTask_NoOutputName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project does not contain an OutputName node..
        /// </summary>
        internal static string WixOutputVersionTask_NoOutputNameNode {
            get {
                return ResourceManager.GetString("WixOutputVersionTask_NoOutputNameNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to resolve Wix project include file &apos;{0}&apos;..
        /// </summary>
        internal static string WixVersionManager_InvalidIncludeFile {
            get {
                return ResourceManager.GetString("WixVersionManager_InvalidIncludeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The wix product variable &apos;{0}&apos; does not contain a version number..
        /// </summary>
        internal static string WixVersionManager_InvalidVersionValue {
            get {
                return ResourceManager.GetString("WixVersionManager_InvalidVersionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wix project does not contain any compilation files..
        /// </summary>
        internal static string WixVersionManager_NoIncludeFilesFound {
            get {
                return ResourceManager.GetString("WixVersionManager_NoIncludeFilesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to identify Wix product version.
        /// </summary>
        internal static string WixVersionManager_ProductVersionNotFound {
            get {
                return ResourceManager.GetString("WixVersionManager_ProductVersionNotFound", resourceCulture);
            }
        }
    }
}
